Test KNN, SVC, LogisticRegression, CatBoost, XGboost with pipeline

# Import libraries

In [1]:
# Changes to all modules will automatically be applied when any cell runs. 
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import numpy as np

import joblib

from statsmodels.api import Logit # type: ignore
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from catboost import CatBoostClassifier
from xgboost import XGBClassifier

from pathlib import Path
import sys

sys.path.append(
    str(Path('..', 'utils_functionality', 'split_utils'))
)
sys.path.append(
    str(Path('..', 'utils_functionality', 'models'))
)

from split_tools import get_train_test
from modelling3_utils import (
    # _prepare_df,
    MLPipeline,
    _create_pipeline,
    StatsModelsEstimator,
)

In [3]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

# Logistic Regression

In [4]:
estimator = LogisticRegression()

ml_pipe = MLPipeline(
    target='splashing',
    estimator=estimator,
    features_to_drop = (
        'Re', 
        'We', 
        'init_volume_fraction',
        'particle_droplet_diameter_ratio',
        'sign_particle_droplet_diameter_ratio',
        'sedimentation_Re',
        'sedimentation_Stk',
        'sign_sedimentation_Stk',
        # 'particle_liquid_density_ratio',
        # 'sign_sedimentation_Re',
        # 'volume_fraction', 
        # 'relative_roughness', 
        # 'inclination',
        # 'wettability',
        # 'K',
    ),
    model_postfix='base',
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features


('sign_sedimentation_Re',
 'particle_liquid_density_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sign_sedimentation_Re',
                                  'particle_liquid_density_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "LogisticRegression"


,0
target,splashing
model,LogisticRegression_splashing_base
holdout_test_accuracy,0.813333
holdout_test_f1,0.865385
holdout_test_roc_auc,0.891204
cv_test_accuracy_median,0.792453
cv_test_f1_median,0.84058
cv_test_roc_auc_median,0.886997


Model saved in ../results/models_modelling3/LogisticRegression_splashing_base


In [5]:
model = joblib.load(
    '../results/models_modelling3/LogisticRegression_splashing_base')
model.predict_proba(
    ml_pipe.get_X_y(ml_pipe.test)[0])[:5]

array([[0.05959526, 0.94040474],
       [0.06389382, 0.93610618],
       [0.04239738, 0.95760262],
       [0.89485934, 0.10514066],
       [0.00426144, 0.99573856]])

In [6]:
estimator = LogisticRegression()

ml_pipe = MLPipeline(
    target='no_fragmentation',
    estimator=estimator,
    features_to_drop = (
        'Re', 
        'We', 
        'init_volume_fraction',
        'particle_droplet_diameter_ratio',
        'sign_particle_droplet_diameter_ratio',
        'sedimentation_Re',
        'sedimentation_Stk',
        'sign_sedimentation_Stk',
        # 'particle_liquid_density_ratio',
        # 'sign_sedimentation_Re',
        # 'volume_fraction', 
        # 'relative_roughness', 
        # 'inclination',
        # 'wettability',
        # 'K',
    ),
    model_postfix='base',
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features


('sign_sedimentation_Re',
 'particle_liquid_density_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sign_sedimentation_Re',
                                  'particle_liquid_density_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "LogisticRegression"


,0
target,no_fragmentation
model,LogisticRegression_no_fragmentation_base
holdout_test_accuracy,0.853333
holdout_test_f1,0.717949
holdout_test_roc_auc,0.925455
cv_test_accuracy_median,0.849057
cv_test_f1_median,0.666667
cv_test_roc_auc_median,0.94188


Model saved in ../results/models_modelling3/LogisticRegression_no_fragmentation_base


# KNClassifier

In [7]:
estimator = KNeighborsClassifier()

ml_pipe = MLPipeline(
    target='splashing',
    estimator=estimator,
    features_to_drop = (
        'Re', 
        'We', 
        'init_volume_fraction',
        'particle_droplet_diameter_ratio',
        'sign_particle_droplet_diameter_ratio',
        'sedimentation_Re',
        'sedimentation_Stk',
        'sign_sedimentation_Stk',
        # 'particle_liquid_density_ratio',
        # 'sign_sedimentation_Re',
        # 'volume_fraction', 
        # 'relative_roughness', 
        # 'inclination',
        # 'wettability',
        # 'K',
    ), 
    model_postfix='base',)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features


('sign_sedimentation_Re',
 'particle_liquid_density_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sign_sedimentation_Re',
                                  'particle_liquid_density_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "KNeighborsClassifier"


,0
target,splashing
model,KNeighborsClassifier_splashing_base
holdout_test_accuracy,0.813333
holdout_test_f1,0.86
holdout_test_roc_auc,0.880787
cv_test_accuracy_median,0.830189
cv_test_f1_median,0.869565
cv_test_roc_auc_median,0.914861


Model saved in ../results/models_modelling3/KNeighborsClassifier_splashing_base


In [8]:
estimator = KNeighborsClassifier()

ml_pipe = MLPipeline(
    target='no_fragmentation',
    estimator=estimator,
    features_to_drop = (
        'Re', 
        'We', 
        'init_volume_fraction',
        'particle_droplet_diameter_ratio',
        'sign_particle_droplet_diameter_ratio',
        'sedimentation_Re',
        'sedimentation_Stk',
        'sign_sedimentation_Stk',
        # 'particle_liquid_density_ratio',
        # 'sign_sedimentation_Re',
        # 'volume_fraction', 
        # 'relative_roughness', 
        # 'inclination',
        # 'wettability',
        # 'K',
    ),
    model_postfix='base',)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features


('sign_sedimentation_Re',
 'particle_liquid_density_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sign_sedimentation_Re',
                                  'particle_liquid_density_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "KNeighborsClassifier"


,0
target,no_fragmentation
model,KNeighborsClassifier_no_fragmentation_base
holdout_test_accuracy,0.88
holdout_test_f1,0.769231
holdout_test_roc_auc,0.949545
cv_test_accuracy_median,0.849057
cv_test_f1_median,0.692308
cv_test_roc_auc_median,0.903846


Model saved in ../results/models_modelling3/KNeighborsClassifier_no_fragmentation_base


In [9]:
model = joblib.load(
    '../results/models_modelling3/KNeighborsClassifier_splashing_base')
model.predict_proba(
    ml_pipe.get_X_y(ml_pipe.test)[0])[:5]

array([[0.8, 0.2],
       [0.2, 0.8],
       [0. , 1. ],
       [0.8, 0.2],
       [0.8, 0.2]])

# SVC

In [10]:
estimator = SVC(probability=True)

ml_pipe = MLPipeline(
    target='splashing',
    estimator=estimator,
    features_to_drop = (
        'Re', 
        'We', 
        'init_volume_fraction',
        'particle_droplet_diameter_ratio',
        'sign_particle_droplet_diameter_ratio',
        'sedimentation_Re',
        'sedimentation_Stk',
        'sign_sedimentation_Stk',
        # 'particle_liquid_density_ratio',
        # 'sign_sedimentation_Re',
        # 'volume_fraction', 
        # 'relative_roughness', 
        # 'inclination',
        # 'wettability',
        # 'K',
    ),
    model_postfix='base',)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features


('sign_sedimentation_Re',
 'particle_liquid_density_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sign_sedimentation_Re',
                                  'particle_liquid_density_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "SVC"


,0
target,splashing
model,SVC_splashing_base
holdout_test_accuracy,0.84
holdout_test_f1,0.884615
holdout_test_roc_auc,0.895833
cv_test_accuracy_median,0.867925
cv_test_f1_median,0.892308
cv_test_roc_auc_median,0.930341


Model saved in ../results/models_modelling3/SVC_splashing_base


In [11]:
model = joblib.load(
    '../results/models_modelling3/SVC_splashing_base')
model.predict_proba(
    ml_pipe.get_X_y(ml_pipe.test)[0])[:5]

array([[0.23544657, 0.76455343],
       [0.03767495, 0.96232505],
       [0.11850165, 0.88149835],
       [0.89566002, 0.10433998],
       [0.04000213, 0.95999787]])

In [12]:
estimator = SVC(probability=True)

ml_pipe = MLPipeline(
    target='no_fragmentation',
    estimator=estimator,
    features_to_drop = (
        'Re', 
        'We', 
        'init_volume_fraction',
        'particle_droplet_diameter_ratio',
        'sign_particle_droplet_diameter_ratio',
        'sedimentation_Re',
        'sedimentation_Stk',
        'sign_sedimentation_Stk',
        # 'particle_liquid_density_ratio',
        # 'sign_sedimentation_Re',
        # 'volume_fraction', 
        # 'relative_roughness', 
        # 'inclination',
        # 'wettability',
        # 'K',
    ),
    model_postfix='base',)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features


('sign_sedimentation_Re',
 'particle_liquid_density_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sign_sedimentation_Re',
                                  'particle_liquid_density_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "SVC"


,0
target,no_fragmentation
model,SVC_no_fragmentation_base
holdout_test_accuracy,0.84
holdout_test_f1,0.684211
holdout_test_roc_auc,0.928182
cv_test_accuracy_median,0.867925
cv_test_f1_median,0.695652
cv_test_roc_auc_median,0.941392


Model saved in ../results/models_modelling3/SVC_no_fragmentation_base


# CatBoost

In [13]:
estimator = CatBoostClassifier(verbose=False)

ml_pipe = MLPipeline(
    target='splashing',
    estimator=estimator,
    features_to_drop = (
        'Re', 
        'We', 
        'init_volume_fraction',
        'particle_droplet_diameter_ratio',
        'sign_particle_droplet_diameter_ratio',
        'sedimentation_Re',
        'sedimentation_Stk',
        'sign_sedimentation_Stk',
        # 'particle_liquid_density_ratio',
        # 'sign_sedimentation_Re',
        # 'volume_fraction', 
        # 'relative_roughness', 
        # 'inclination',
        # 'wettability',
        # 'K',
    ),
    model_postfix='base',)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features


('sign_sedimentation_Re',
 'particle_liquid_density_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sign_sedimentation_Re',
                                  'particle_liquid_density_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "CatBoostClassifier"


,0
target,splashing
model,CatBoostClassifier_splashing_base
holdout_test_accuracy,0.88
holdout_test_f1,0.910891
holdout_test_roc_auc,0.946759
cv_test_accuracy_median,0.886792
cv_test_f1_median,0.909091
cv_test_roc_auc_median,0.950464


Model saved in ../results/models_modelling3/CatBoostClassifier_splashing_base


In [14]:
model = joblib.load(
    '../results/models_modelling3/CatBoostClassifier_splashing_base')
model.predict_proba(
    ml_pipe.get_X_y(ml_pipe.test)[0])[:5]

array([[0.04080068, 0.95919932],
       [0.11544159, 0.88455841],
       [0.03240344, 0.96759656],
       [0.96022457, 0.03977543],
       [0.09204319, 0.90795681]])

In [15]:
estimator = CatBoostClassifier(verbose=False)

ml_pipe = MLPipeline(
    target='no_fragmentation',
    estimator=estimator,
    features_to_drop = (
        'Re', 
        'We', 
        'init_volume_fraction',
        'particle_droplet_diameter_ratio',
        'sign_particle_droplet_diameter_ratio',
        'sedimentation_Re',
        'sedimentation_Stk',
        'sign_sedimentation_Stk',
        # 'particle_liquid_density_ratio',
        # 'sign_sedimentation_Re',
        # 'volume_fraction', 
        # 'relative_roughness', 
        # 'inclination',
        # 'wettability',
        # 'K',
    ),
    model_postfix='base',)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features


('sign_sedimentation_Re',
 'particle_liquid_density_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sign_sedimentation_Re',
                                  'particle_liquid_density_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "CatBoostClassifier"


,0
target,no_fragmentation
model,CatBoostClassifier_no_fragmentation_base
holdout_test_accuracy,0.906667
holdout_test_f1,0.829268
holdout_test_roc_auc,0.978182
cv_test_accuracy_median,0.886792
cv_test_f1_median,0.8
cv_test_roc_auc_median,0.968864


Model saved in ../results/models_modelling3/CatBoostClassifier_no_fragmentation_base


# XGBoost

In [16]:
estimator = XGBClassifier()

ml_pipe = MLPipeline(
    target='splashing',
    estimator=estimator,
    features_to_drop = (
        'Re', 
        'We', 
        'init_volume_fraction',
        'particle_droplet_diameter_ratio',
        'sign_particle_droplet_diameter_ratio',
        'sedimentation_Re',
        'sedimentation_Stk',
        'sign_sedimentation_Stk',
        # 'particle_liquid_density_ratio',
        # 'sign_sedimentation_Re',
        # 'volume_fraction', 
        # 'relative_roughness', 
        # 'inclination',
        # 'wettability',
        # 'K',
    ),
    model_postfix='base',)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features


('sign_sedimentation_Re',
 'particle_liquid_density_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sign_sedimentation_Re',
                                  'particle_liquid_density_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "XGBClassifier"


,0
target,splashing
model,XGBClassifier_splashing_base
holdout_test_accuracy,0.866667
holdout_test_f1,0.901961
holdout_test_roc_auc,0.944059
cv_test_accuracy_median,0.886792
cv_test_f1_median,0.90625
cv_test_roc_auc_median,0.934211


Model saved in ../results/models_modelling3/XGBClassifier_splashing_base


In [17]:
estimator = XGBClassifier()

ml_pipe = MLPipeline(
    target='no_fragmentation',
    estimator=estimator,
    features_to_drop = (
        'Re', 
        'We', 
        'init_volume_fraction',
        'particle_droplet_diameter_ratio',
        'sign_particle_droplet_diameter_ratio',
        'sedimentation_Re',
        'sedimentation_Stk',
        'sign_sedimentation_Stk',
        # 'particle_liquid_density_ratio',
        # 'sign_sedimentation_Re',
        # 'volume_fraction', 
        # 'relative_roughness', 
        # 'inclination',
        # 'wettability',
        # 'K',
    ),
    model_postfix='base',)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features


('sign_sedimentation_Re',
 'particle_liquid_density_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sign_sedimentation_Re',
                                  'particle_liquid_density_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "XGBClassifier"


,0
target,no_fragmentation
model,XGBClassifier_no_fragmentation_base
holdout_test_accuracy,0.866667
holdout_test_f1,0.761905
holdout_test_roc_auc,0.96
cv_test_accuracy_median,0.924528
cv_test_f1_median,0.846154
cv_test_roc_auc_median,0.970696


Model saved in ../results/models_modelling3/XGBClassifier_no_fragmentation_base


In [18]:
model = joblib.load(
    '../results/models_modelling3/XGBClassifier_splashing_base')
model.predict_proba(
    ml_pipe.get_X_y(ml_pipe.test)[0])[:5]

array([[0.98380095, 0.01619903],
       [0.01922667, 0.9807733 ],
       [0.0012908 , 0.9987092 ],
       [0.22033495, 0.77966505],
       [0.98519635, 0.01480367]], dtype=float32)