Test KNN, SVC, LogisticRegression, CatBoost, XGboost with pipeline

# Import libraries

In [1]:
# Changes to all modules will automatically be applied when any cell runs. 
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import numpy as np

import joblib

from statsmodels.api import Logit # type: ignore
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from catboost import CatBoostClassifier
from xgboost import XGBClassifier

from pathlib import Path
import sys

sys.path.append(
    str(Path('..', 'utils_functionality', 'split_utils'))
)
sys.path.append(
    str(Path('..', 'utils_functionality', 'models'))
)

from split_tools import get_train_test
from modelling3_utils import (
    # _prepare_df,
    MLPipeline,
    _create_pipeline,
    StatsModelsEstimator,
)

In [3]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

# Logistic Regression

In [4]:
estimator = LogisticRegression()

ml_pipe = MLPipeline(
    target='splashing',
    estimator=estimator,
    features_to_drop = (
        'Re', 
        'We', 
        'init_volume_fraction',
        'particle_droplet_diameter_ratio', 
        'sedimentation_Re',
        # 'particle_liquid_density_ratio',
        'sedimentation_Stk'
        # 'sign_sedimentation_Re',
        # 'volume_fraction', 
        # 'relative_roughness', 
        # 'inclination',
        # 'wettability',
    ),
    model_postfix='base',
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features


None

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sign_sedimentation_Re',
                                  'particle_liquid_density_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "LogisticRegression"


,0
dataset,df_dimless
target,splashing
model,LogisticRegression_splashing_base
params,"{'estimator': LogisticRegression(), 'source_fe..."
holdout_test_accuracy,0.813333
holdout_test_precision,0.803571
holdout_test_recall,0.9375
holdout_test_f1,0.865385
holdout_test_roc_auc,0.891204
holdout_train_accuracy,0.814815


Model saved in ../results/models_modelling3/LogisticRegression_splashing_base


In [5]:
model = joblib.load(
    '../results/models_modelling3/LogisticRegression_splashing_base')
model.predict_proba(
    ml_pipe.get_X_y(ml_pipe.test)[0])[:5]

array([[0.05959526, 0.94040474],
       [0.06389382, 0.93610618],
       [0.04239738, 0.95760262],
       [0.89485934, 0.10514066],
       [0.00426144, 0.99573856]])

# KNClassifier

In [6]:
estimator = KNeighborsClassifier()

ml_pipe = MLPipeline(
    target='splashing',
    estimator=estimator,
    features_to_drop = (
        'Re', 
        'We', 
        'init_volume_fraction',
        'particle_droplet_diameter_ratio', 
        'sedimentation_Re',
        # 'particle_liquid_density_ratio',
        'sedimentation_Stk'
        # 'sign_sedimentation_Re',
        # 'volume_fraction', 
        # 'relative_roughness', 
        # 'inclination',
        # 'wettability',
    ), model_postfix='base',)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features


None

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sign_sedimentation_Re',
                                  'particle_liquid_density_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "KNeighborsClassifier"


,0
dataset,df_dimless
target,splashing
model,KNeighborsClassifier_splashing_base
params,"{'estimator': KNeighborsClassifier(), 'source_..."
holdout_test_accuracy,0.813333
holdout_test_precision,0.826923
holdout_test_recall,0.895833
holdout_test_f1,0.86
holdout_test_roc_auc,0.880787
holdout_train_accuracy,0.915825


Model saved in ../results/models_modelling3/KNeighborsClassifier_splashing_base


In [7]:
model = joblib.load(
    '../results/models_modelling3/KNeighborsClassifier_splashing_base')
model.predict_proba(
    ml_pipe.get_X_y(ml_pipe.test)[0])[:5]

array([[0.4, 0.6],
       [0. , 1. ],
       [0. , 1. ],
       [1. , 0. ],
       [0. , 1. ]])

# SVC

In [8]:
estimator = SVC(probability=True)

ml_pipe = MLPipeline(
    target='splashing',
    estimator=estimator,
    features_to_drop = (
        'Re', 
        'We', 
        'init_volume_fraction',
        'particle_droplet_diameter_ratio', 
        'sedimentation_Re',
        # 'particle_liquid_density_ratio',
        'sedimentation_Stk'
        # 'sign_sedimentation_Re',
        # 'volume_fraction', 
        # 'relative_roughness', 
        # 'inclination',
        # 'wettability',
    ), model_postfix='base',)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features


None

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sign_sedimentation_Re',
                                  'particle_liquid_density_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "SVC"


,0
dataset,df_dimless
target,splashing
model,SVC_splashing_base
params,"{'estimator': SVC(probability=True), 'source_f..."
holdout_test_accuracy,0.84
holdout_test_precision,0.821429
holdout_test_recall,0.958333
holdout_test_f1,0.884615
holdout_test_roc_auc,0.895833
holdout_train_accuracy,0.885522


Model saved in ../results/models_modelling3/SVC_splashing_base


In [9]:
model = joblib.load(
    '../results/models_modelling3/SVC_splashing_base')
model.predict_proba(
    ml_pipe.get_X_y(ml_pipe.test)[0])[:5]

array([[0.22335218, 0.77664782],
       [0.03001266, 0.96998734],
       [0.10504737, 0.89495263],
       [0.91303777, 0.08696223],
       [0.03203911, 0.96796089]])

# CatBoost

In [10]:
estimator = CatBoostClassifier(verbose=False)

ml_pipe = MLPipeline(
    target='splashing',
    estimator=estimator,
    features_to_drop = (
        'Re', 
        'We', 
        'init_volume_fraction',
        'particle_droplet_diameter_ratio', 
        'sedimentation_Re',
        # 'particle_liquid_density_ratio',
        'sedimentation_Stk'
        # 'sign_sedimentation_Re',
        # 'volume_fraction', 
        # 'relative_roughness', 
        # 'inclination',
        # 'wettability',
    ), model_postfix='base',)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features


None

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sign_sedimentation_Re',
                                  'particle_liquid_density_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "CatBoostClassifier"


,0
dataset,df_dimless
target,splashing
model,CatBoostClassifier_splashing_base
params,{'estimator': <catboost.core.CatBoostClassifie...
holdout_test_accuracy,0.88
holdout_test_precision,0.867925
holdout_test_recall,0.958333
holdout_test_f1,0.910891
holdout_test_roc_auc,0.946759
holdout_train_accuracy,0.996633


Model saved in ../results/models_modelling3/CatBoostClassifier_splashing_base


In [11]:
model = joblib.load(
    '../results/models_modelling3/CatBoostClassifier_splashing_base')
model.predict_proba(
    ml_pipe.get_X_y(ml_pipe.test)[0])[:5]

array([[0.04080068, 0.95919932],
       [0.11544159, 0.88455841],
       [0.03240344, 0.96759656],
       [0.96022457, 0.03977543],
       [0.09204319, 0.90795681]])

# XGBoost

In [12]:
estimator = XGBClassifier()

ml_pipe = MLPipeline(
    target='splashing',
    estimator=estimator,
    features_to_drop = (
        'Re', 
        'We', 
        'init_volume_fraction',
        'particle_droplet_diameter_ratio', 
        'sedimentation_Re',
        # 'particle_liquid_density_ratio',
        'sedimentation_Stk'
        # 'sign_sedimentation_Re',
        # 'volume_fraction', 
        # 'relative_roughness', 
        # 'inclination',
        # 'wettability',
    ), model_postfix='base',)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features


None

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sign_sedimentation_Re',
                                  'particle_liquid_density_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "XGBClassifier"


,0
dataset,df_dimless
target,splashing
model,XGBClassifier_splashing_base
params,"{'estimator': XGBClassifier(base_score=None, b..."
holdout_test_accuracy,0.866667
holdout_test_precision,0.851852
holdout_test_recall,0.958333
holdout_test_f1,0.901961
holdout_test_roc_auc,0.944059
holdout_train_accuracy,0.996633


Model saved in ../results/models_modelling3/XGBClassifier_splashing_base


In [13]:
model = joblib.load(
    '../results/models_modelling3/XGBClassifier_splashing_base')
model.predict_proba(
    ml_pipe.get_X_y(ml_pipe.test)[0])[:5]

array([[0.00789207, 0.9921079 ],
       [0.03681272, 0.9631873 ],
       [0.00534171, 0.9946583 ],
       [0.9872422 , 0.01275775],
       [0.0543167 , 0.9456833 ]], dtype=float32)